### ISSUE TITLE
Custom response

### ISSUE THREAD

**Issue by fatagun** [Xabaril/BeatPulse#100]
Hello,

is it possible to customize end point response?

Currently I am registering sql server, redis and rabbitmq health checks. If all the health checks are OK, I would like to return something as following:

```
{
     "health" : "healthy"
}
```

If one of the health checks fails, I would like to return a different message etc.

How can I do this?

**Comment by unaizorrilla** [comment]
Hi @fatagun

In  new Asp.Net Core 2.2 HealthChecks you can customize the response and continue using this HealthChecks, please review:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks

 With BeatPulse (mantained for 2.1 .net core) this is not an option.

**Comment by fatagun** [comment]
Thanks.
