### ISSUE TITLE
Liveness packages separated versions

### ISSUE THREAD

**Issue by CarlosLanderas** [Xabaril/BeatPulse#15]
Separate packages versions in dependencies props so users don't update Liveness packages that contain same bytes when main library increases version and viceversa.

**Comment by Xabaril** [comment]
Yeap, each package need a specific version property on dependencies props file! Up for grabs!

**Comment by CarlosLanderas** [comment]
I'll take it, starting packages versions with the current global version.

**Comment by unaizorrilla** [comment]
Merged
