### ISSUE TITLE
Well formated json output messages

### ISSUE THREAD

**Issue by unaizorrilla** [Xabaril/BeatPulse#25]
At this moment the json output is not using the CamelCaseNamesContractResolver, add this into json output messages. This change affect to BeatPulse-UI but now is on development, is good moment to do.

**Comment by CarlosLanderas** [comment]
I'll take it as I have to make changes in the UI html binding.

**Comment by unaizorrilla** [comment]
The UI is down on my branch due to the latest changes I perform. Please wait to my push and feel free. 
Thanks Carlos!
