### ISSUE TITLE
Consistency with EnableDetailedOutput

### ISSUE THREAD

**Issue by hbiarge** [Xabaril/BeatPulse#31]
First of all, congratulations for this amazing library!

Reviewing the code I can see that, by design, in the first unhealthy liveness result, the library stops processing the next registered liveness and returns a 503 response. I can understand the motivation if you don´t have the *options.EnableDetailedOutput* configuration enabled. But if this *options.EnableDetailedOutput* configuration is enabled, I would expect a 200 response with the information of all registered liveness results (the ones that are ok and the ones that not).

Make sense this behavior?

**Comment by Xabaril** [comment]
Hi @hbiarge 

Well, the idea of BeatPulse is to be used as a liveness uri from k8s/swarm and similar. Most of these use the status code to restart the pod/container not the content of the response.

When the service is not available ( 503 ) BeatPulse return the first not running checker and break the task. Are you suggesting don't break the task and check all liveness?

**Comment by hbiarge** [comment]
Yes, exactly that, but depending on the *options.EnableDetailedOutput* value.

My point is that the current behavior seems correct if you are not interested in the detailed information. The first failed checker break the Task and return a 503 so the orchestrator can kill the container and start another one.
But if you enable *options.EnableDetailedOutput* I would expect that all the checkers run and receive the complete information in the response body. As you say, may be a good point maintain the 503 status code if some check fails, in order to be consistent with the behavior of the library when *options.EnableDetailedOutput* is disabled, but get the information of ALL checkers. 
I have been testing the library in the context of a middleware application in a complex system with a lot of dependencies and the information shown in the health endpoint is not consistent when different dependencies fail and *options.EnableDetailedOutput* is enabled.

**Comment by Xabaril** [comment]
Sound ok for me, labeled as up for grabs!

**Comment by Xabaril** [comment]
Commited, thanks @hbiarge for this suggestion!
