### ISSUE TITLE
Add possiblity of use trackers/logs as Application Insights for metrics and historic info

### ISSUE THREAD

**Issue by lfraile** [Xabaril/BeatPulse#42]
Add the possibility of using Application Insights or other APM to record liveness information events and metrics.

This would allow the possibility of having and history of liveness information, like which are unreliable services, as well as metrics for any *pulse* milliseconds ellapsed.

This should be added dynamically and support from zero to n trackers.

**Comment by unaizorrilla** [comment]
Hi Luis,

Can you explain more "allow the possibility of having and history of liveness information". This tracker track de "service availability" or metrics like "liveness excution time" etc?

Unai

**Comment by lfraile** [comment]
Sure.

With the Application Insights Tracker, you can check whole history of all BeatPulse calls and it's result, making it so easy to have historical information of it, via Application Insights events information:
![image](https://user-images.githubusercontent.com/1047038/40114474-58984a6a-590d-11e8-9e48-837ae5648476.png)

Also, adding the milliseconds info taken from BeatPulse, and adding it to the event information, we can have custom metrics on which "pulses" are taking more time, also with history info, via metrics on Application Insights:
![image](https://user-images.githubusercontent.com/1047038/40114552-a0c433b2-590d-11e8-9039-b438c12b9eea.png)

The whole point of this also, is to add a new extensibility point, which allows developers to create and add his own trackers for other APM like New Relic, to be able to use this info with the whole monitoring info from their own applications.

**Comment by unaizorrilla** [comment]
Hi @lfraile ,

Sounds good, waiting your PR!

**Comment by unaizorrilla** [comment]
Thanks for this PR, on master with 7140bd4880966f2d41b7dd5364fb4df8119357e1
