### ISSUE TITLE
Protection level of BeatPulseFilter + BeatPulseMiddleware

### ISSUE THREAD

**Issue by stephenpope** [Xabaril/BeatPulse#52]
I am building an application (for sake of getting into pointless detail) I cant use the ` UseBeatPulse()` Webhost extension.

I was hoping to be able register the `IStartupFilter` / `BeatPulseFilter` myself but this is private/internal.

So I thought I would register the middleware `BeatPulseMiddleware` myself but this is also private/internal.

Is there a reason for this level of security on these classes? I am keen to use BeatPulse but this has de-railed any progress I can make currently :)

**Comment by unaizorrilla** [comment]
Hi  @stephenpope, this is not about "security", is about don't expose internal things. But, your are right, the BeatPulsePulseMiddleware should be public as asp.net usually does . In next version, probably tomorrow, I will make this change. Hope this help!

Thanks for fill this issue!!

Unai

**Comment by unaizorrilla** [comment]
Fixed on #70de175d7b44b1c8b779de8913c3bac860ea6841 BeatPulseMiddleware is public from version 1.7.1

**Comment by stephenpope** [comment]
Thanks for the quick fix :D

**Comment by unaizorrilla** [comment]
hope this help!
