### ISSUE TITLE
Versioning, BeatPulse, UI and liveness Packages...

### ISSUE THREAD

**Issue by unaizorrilla** [Xabaril/BeatPulse#54]
At this moment, each BeatPulse Liveness Package, BeatPulse, UI and trackers have specific version numbers for each package. As a matter of fact between BeatPulse, UI, liveness and trackers exist a strong relationship due the contract of LivenessResult.

The strategy we have now does not seem adequate because there is no way to know which version of UI is valid for a specific version of the BeatPulse, e.g.

**I'd like to know if anyone has any idea how best to address this problem?**

**Comment by unaizorrilla** [comment]
Hi  @x2764tech 

 Thanks for the link reference and for the comments, I know semver and is on the solution right know.

**Comment by x2764tech** [comment]
You could also use a `Directory.Build.props` to keep them in sync (see https://www.thomaslevesque.com/2017/09/18/common-msbuild-properties-and-items-with-directory-build-props/ and https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets)

**Comment by unaizorrilla** [comment]
Hi @x2764tech 

This project use Directory.Build.props from the scratch!
