### ISSUE TITLE
NuGet package BeatPulse.SqlServer (v1.4.0) breaks with package BeatPulse (v1.7.1)

### ISSUE THREAD

**Issue by eneunaber** [Xabaril/BeatPulse#55]
I was following the BeatPulse documentation and when I ran the application, it throws an error on this line

**Code**
`    services.AddBeatPulse(setup =>
    {
        //add sql server liveness
        setup.AddSqlServer("your-connection-string");
    });`

**Exception**
`System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'BeatPulse.Core.BeatPulseContext BeatPulse.Core.BeatPulseContext.Add(BeatPulse.Core.IBeatPulseLiveness)'.
  Source=BeatPulse.SqlServer
  StackTrace:
   at BeatPulse.BeatPulseContextExtensions.AddSqlServer(BeatPulseContext context, String connectionString, String defaultPath)
   at BeatPulseDemo.Startup.<ConfigureServices>b__4_0(BeatPulseContext setup) in C:\Projects\Sandbox\BeatPulseDemo\BeatPulseDemo\Startup.cs:line 33
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddBeatPulse(IServiceCollection services, Action`1 setup)
   at BeatPulseDemo.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\Sandbox\BeatPulseDemo\BeatPulseDemo\Startup.cs:line 30
`
**Experiments**
I cloned the BeatPulse repository and directly added the projects **BeatPulse** and **BeatPulse.SqlServer** to my project and added the corresponding project references. When I ran the application this way I did not receive an error. 

To attempt to reproduce I created a simple project with step by step commits to demonstrate the problem. The repo can be found here: [https://github.com/eneunaber/BeatPulseDemo](url). I was able to fix the problem by downgrading to BeatPulse (v1.4.5). 

**Observation**
This was the last day the two packages were deployed on the same day
BeatPulse (v1.4.5) : Thursday, May 10, 2018 (5/10/2018)
BeatPulse.SqlServer (v1.4.0) : Thursday, May 10, 2018 (5/10/2018)

Given that my experiment with cloning and adding the projects to my existing project fixed the problem. It maybe as simple as publishing new NuGet packages.

**Comment by unaizorrilla** [comment]
Hi @eneunaber 

Well on 1.7.X we perform a refactor with different features for registering liveness. In my mind, all liveness are updated with a new version but :-( 
Right now **a new version for liveness package is on nuget, 1.7.0,  and this solve the problem, please confirm!**. 
This history is related with #54 in order to set a improved versioning strategy..

Thanks for fill the issue
