### ISSUE TITLE
Dead link: nuget package description

### ISSUE THREAD

**Issue by JoschaHemlep** [Xabaril/BeatPulse#62]
https://www.nuget.org/packages/BeatPulse/

"BeatPulse is a health check library for ASP.NET Core Applications.For more information see **http://github.com/Xabaril/CheckPulse**"

Wrong/Dead link

**Comment by CarlosLanderas** [comment]
Thanks for reporting the wrong link. @unaizorrilla can you change it?

**Comment by unaizorrilla** [comment]
done on 1d59d93be26814e59b6186a79fe3d0f9f50c7642 commit.
