### ISSUE TITLE
.Net Framework support

### ISSUE THREAD

**Issue by rogerbramon** [Xabaril/BeatPulse#63]
Hi,

We were about to implement a health check solution very similar to BeatPulse. However, we're not ready to migrate to .Net Core unfortunately. Do you think it's doable to add support to .Net Framework?

**Comment by eiximenis** [comment]
Hi @rogerbramon 

I think this should be doable because we are using netstandard. Which:

- versions of netfx are expected to be supported?
- asp.net frameworks? MVC? WebApi? Webforms?

**Comment by hasansachdev** [comment]
what would be the .net framework equivalent of this?
```
public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
               .UseBeatPulse(options=>
                {
                   options.ConfigurePath(path:"health") //default hc
                        .ConfigureTimeout(milliseconds:1500) // default -1 infinitely
                        .ConfigureDetailedOutput(detailedOutput:true,includeExceptionMessages:true); //default (true,false)
                }).UseStartup<Startup>().Build();
```
