### ISSUE TITLE
Custom status code acceptance

### ISSUE THREAD

**Issue by kevin93w** [Xabaril/BeatPulse#67]
Hi there!

Currently in the process of implementing BeatPulse and using it for different kinds of external services. For one example we are using an API endpoint that isn't fully compliant with REST standards. Because of this it is either necessary to request using a custom header (which will return 200OK) and if the header is absent it will return another status code, not in 200-299 range.

Currently it is not possible to either send a custom header, or passing the expected status code using the AddUrlGroup methods. Is it possible to update the package and implement either of these functionalities?

Thanks in advance!

**Comment by unaizorrilla** [comment]
Merged  #68

**Comment by unaizorrilla** [comment]
I need update version number and create a new tag, next day morning I can do it.

**Comment by kevin93w** [comment]
Great man! Will test it as soon as you have published the changes.

**Comment by CarlosLanderas** [comment]
@kevin93w, The Beatpulse release 2.1.2 has been created
Uris liveness supports now custom status code acceptance in version 2.1.1
