### ISSUE TITLE
[BeatPulse-UI] Impossible to display data

### ISSUE THREAD

**Issue by Necriis** [Xabaril/BeatPulse#83]
The UI can't display the data: `Could not retrieve liveness data`
The `/hc` query returns a valid response (200 OK)
```json
{
  "checks": [
    {
      "name": "self",
      "message": "OK",
      "exception": null,
      "elapsed": "00:00:00.0038054",
      "run": true,
      "path": "_self",
      "isHealthy": true
    },
    {
      "name": "SqlServerLiveness",
      "message": "OK",
      "exception": null,
      "elapsed": "00:00:00.0633807",
      "run": true,
      "path": "sqlserver",
      "isHealthy": true
    }
  ],
  "startedAtUtc": "2018-11-20T13:47:43.1583229Z",
  "endAtUtc": "2018-11-20T13:47:43.2454719Z",
  "code": 200,
  "reason": ""
}
```

But I have an error in the console: `beatpulse-bundle.js TypeError: "A.filter is not a function"`
It seems to refer to [BeatPulse/src/BeatPulse.UI/Client/components/LivenessPage.tsx line 54](https://github.com/Xabaril/BeatPulse/blob/7fe5019a09d125bc5e1ba4482053ee673e902974/src/BeatPulse.UI/Client/components/LivenessPage.tsx).
Any idea ?

**Comment by unaizorrilla** [comment]
Hi @Necriis 

@CarlosLanderas could you follow this issue?

**Comment by CarlosLanderas** [comment]
Hello @Necriis , I have been configuring a project and I am unable to reproduce this bug.

Although the call to the /hc segment is working, can you check if the xhr request that beatpulse UI is performing against the beatpulse-api endpoint is working correctly? Check it with F12 chrome tools and come back to me please.

Thank you

**Comment by Necriis** [comment]
I tried again with a new asp dotnet core project, I added BeatPulse.SqlServer and BeatPulse.UI, setup with the example config from the project readme, and same issue again.
The xhr request that beatpulse UI is performing against the beatpulse-api is the one I posted in my first post, and is working properly...
I tried on Firefox, Vivaldi, even on Edge... no success

**Comment by CarlosLanderas** [comment]
Thanks @Necriis, Let me test it further and I come back to you. 👍

**Comment by Necriis** [comment]
The sample works fine, but I forgot to specify a point... my app is deployed in a linux docker container. It seems to be the only difference.

**Comment by unaizorrilla** [comment]
Hi @Necriis

Can you check https://github.com/Xabaril/BeatPulse/blob/master/doc/ui-docker.md yo see how configure UI on Docker ?

**Comment by Necriis** [comment]
Ok, starting from the sample (BeatPulseIntegratedUI):
I add the BeatPulse Nuget
```xml
<ItemGroup>
  <PackageReference Include="BeatPulse" Version="3.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```
I add detailedOutput
```csharp
WebHost.CreateDefaultBuilder(args)
    .UseBeatPulse(options =>
    {
        options.ConfigureDetailedOutput(detailedOutput: true, includeExceptionMessages: false);
    })
    .UseStartup<Startup>();
```
I configure the API path in Startup class
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseBeatPulseUI(apiOptions =>
    {
        apiOptions.BeatPulseApiPath = "/hc";
    });
}
```
And add BeatPulse service
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddBeatPulseUI();
    services.AddBeatPulse();
}
```
I run the app and the error is here.

**Comment by Necriis** [comment]
@unaizorrilla I configured my project with the UI docker image and it works great. However, in this context, I have to configure manually each liveness.
With the NuGet version, I only configure the main BeatPulseApiPath in the UseBeatPulseUI extension method and let him _discover_ the livenesses.

**Comment by CarlosLanderas** [comment]
@Necriis, other user suffered the same problem here:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/18

Make sure you are pointing to the health-ui endpoint

**Comment by dungtm007** [comment]
Hi @CarlosLanderas,
What do you mean by  pointing to the health-ui endpoint?

Default BeatPulse endpoint is "/hc"

Is that the thing I should do to config BeatPulseUI API Path?
` app.UseBeatPulseUI(apiOptions => {
                apiOptions.BeatPulseApiPath = "/hc";
            });`
