### ISSUE TITLE
UI behind reverse proxy

### ISSUE THREAD

**Issue by fleed** [Xabaril/BeatPulse#85]
I'm trying to publish the ui behind Nginx creating a specific subpath for the BeatPulse web application, but all the ui related resources cannot be loaded.
I'm trying to redirect from `https://myserver.com/monitor` to `http://localhost:{app-specific-port}`.

In the file `BeatPulse/src/BeatPulse.UI/Assets/index.html` I see some absolute paths:

- `/ui/resources/bootstrap-min.css`
- `/ui/resources/beatpulse.css`
- `/ui/resources/vendors-dll.js`
- `/ui/resources/beatpulse-bundle.js`

Are they somehow replaced if the UI is not placed at the root of the website? Maybe an option to be specified in the setup methods?

**Comment by CarlosLanderas** [comment]
@fleed  you are right, all the resources are served in /ui/resources segment.

Appart from the redirection of /monitor to the beatpulse url, could you add a redirection to the resources segment?

`https://myserver.com/monitor/ui/resources`
 to
 `http://localhost:{app-specific-port}/ui/resources`

**Comment by unaizorrilla** [comment]
Hi

@fleed  can I close this issue?

**Comment by GustavoFonsecaDeAlmeida** [comment]
You can use the Last fature at version 3.0.2. Use apiOptions properties to change.

**Comment by fleed** [comment]
@GustavoFonsecaDeAlmeida is 3.0.2 released?

**Comment by CarlosLanderas** [comment]
We are having trouble deploying NuGets with AppVeyor:

https://github.com/NuGet/Home/issues/6082

Im working on it. If we can't fix it we will deploy UI 3.0.2 manually.

**Comment by CarlosLanderas** [comment]
BeatPulse UI 3.0.2 has been published to Nuget @fleed  @GustavoFonsecaDeAlmeida. If you can check it works properly I close the issue. Thanks

**Comment by karlmtc** [comment]
Could this also be related with #77?

**Comment by CarlosLanderas** [comment]
In this case the issue was with the UI resources (js, css and static files). You have no problem using an empty path to register this kind of assets

**Comment by fleed** [comment]
@CarlosLanderas I tested, but it didn't actually solve my use case.
I think that the problem is `Core/UIResourceMapper.cs` @ line 26.

I'm observing the following:

I'm browsing `http://localhost/monitor/beatpulse-ui` that it is translated by **nginx** to `http://localhost:19081/BeatPulseServiceFabricApp/BeatPulseApp/beatpulse-ui`.
So far so good, I can get the expected html page.

Inspecting the source code I can find the expected links (e.g. `<link rel="stylesheet" href="/monitor/ui/resources/bootstrap-min.css">`).

The problem is that the `/monitor` segment is removed by **nginx**.
**nginx** forwards the request to `http://localhost:19081/BeatPulseServiceFabricApp/BeatPulseApp/ui/resources/bootstrap-min.css` (correct behaviour IMHO), but the path is not found (`404`).
I can see that the following path is correctly returning the resource:
`http://localhost:19081/BeatPulseServiceFabricApp/BeatPulseApp/monitor/ui/resources/bootstrap-min.css`

Additionally, testing the following link `http://localhost/monitor/monitor/ui/resources/beatpulse.css` returns the resource as well.

**Comment by CarlosLanderas** [comment]
@fleed  Are you configuring UseBeatPulseUI with the resources path set to /monitor?. That should not work behind nginx. Try configuring it to **empty string** so the resources are served from the root where you are served the html page.

**Comment by fleed** [comment]
@CarlosLanderas it is successfully working, but I need the following nginx configuration entries:

```
location /beatpulse/ui/ {
            proxy_pass http://localhost:19081/BeatPulseServiceFabricApp/BeatPulseApp/beatpulse/ui/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Forwarded-For $remote_addr;
            add_header X-Upstream $upstream_addr;
        }
        location /beatpulse-api {
            proxy_pass http://localhost:19081/BeatPulseServiceFabricApp/BeatPulseApp/beatpulse-api;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Forwarded-For $remote_addr;
            add_header X-Upstream $upstream_addr;
        }
        location /monitor/ {
            proxy_pass http://localhost:19081/BeatPulseServiceFabricApp/BeatPulseApp/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Forwarded-For $remote_addr;
            add_header X-Upstream $upstream_addr;
        }
```

My BeatPulseUI is configured like this:

```
            app.UseBeatPulseUI(options => options.BeatPulseResourcePath = "/beatpulse/ui/resources");
```

avoiding any conflicts with other /ui assets.

Maybe I'm misconfiguring the system and someone can suggest a simpler configuration, but if that's the way to make it work in this context (nginx -> ServiceFabric -> BeatPulse), I consider it a little bit ugly. If there is a virtual path serving the BeatPulse website, it should be IMHO totally transparent to the application (or at least configurable).

I can close this issue as I find a workaround for the original problem and you can reopen if you consider additional work.

Thank you for support and for the work on this great project.

**Comment by CarlosLanderas** [comment]
Thanks for the feedback @fleed  :)
