### ISSUE TITLE
Incorrect NuGet Package

### ISSUE THREAD

**Issue by shanselman** [Xabaril/BeatPulse#90]
You might want to remove this package or unlist it https://www.nuget.org/packages/BeatPulse.UI.dll/1.0.0/

**Comment by CarlosLanderas** [comment]
Thanks for the warning @shanselman. That package is not ours. I think it might be from one of our latest contributors.

@GustavoFonsecaDeAlmeida based on the package owner name I think it might be yours. Could you unlist that package? It can be misleading for users

**Comment by GustavoFonsecaDeAlmeida** [comment]
Sorry, I Will unlist. I make this to test some things. I forgot to delete.

**Comment by GustavoFonsecaDeAlmeida** [comment]
@CarlosLanderas

**Comment by GustavoFonsecaDeAlmeida** [comment]
![screenshot_20181206-224908](https://user-images.githubusercontent.com/34376408/49620753-72772400-f9a9-11e8-8934-a3d91dcda1a5.jpg)

**Comment by GustavoFonsecaDeAlmeida** [comment]
Can use this to make a question?
The Last merge dont upload a new version to nugget?  The Last version at nuget is 3.0.1 @CarlosLanderas

**Comment by CarlosLanderas** [comment]
@GustavoFonsecaDeAlmeida we are having trouble with AppVeyor deploying to smbsrc.net due to a certificate expiration. You can follow it here:

https://github.com/NuGet/Home/issues/6082

Closing the issue :)
