### ISSUE TITLE
Question: Can beatpulse be used with MVC 5 apps and full framework windows services?

### ISSUE THREAD

**Issue by cquillen** [Xabaril/BeatPulse#92]
I realize this is intended for Core, but we are trying to implement the health check pattern for all our internal applications.  Most of these are written on full framework with MVC 5.  Some are just TopShelf based windows services and don't have a web server at all.

I'm looking around for libraries to help with this effort.  Would be be possible to use parts of this project such as the actual checkers (sql server, rabbitmq, etc) running outside of asp.net core?

**Comment by unaizorrilla** [comment]
Nope, BeatPulse is only for asp.net core 2.1 and not future features are planned. Please read the readme.md.

**Comment by cquillen** [comment]
This seems to indicate otherwise:

https://github.com/Xabaril/BeatPulse/issues/73

The comments suggest that the OWIN middleware is done.

**Comment by unaizorrilla** [comment]
This is true, but after Microsoft announce HealthChecks for ASP.NET Core 2.2 the Xabaril team decide to port all liveness into this new abstractions and discontinue this project for future release, only 3.0 maintainement.
