### ISSUE TITLE
BeatPulse UI memory leak

### ISSUE THREAD

**Issue by wormst** [Xabaril/BeatPulse#95]
After adding a BeatPulse.UI and valid configuration, ASP.NET Core application started to fail due to Out of memory exception.

I have also made a simple test using a sample project from this repository and the result is the same. Memory used by the process continuosly grows in time.

**Comment by wormst** [comment]
Yes, I'm using latest version (3.0.2).
Initial profiling with dotTrace pointed to UIApiEndpointMiddleware:
![image](https://user-images.githubusercontent.com/9641643/50090503-01393b80-0209-11e9-9301-879a5d074dac.png)

**Comment by unaizorrilla** [comment]
Thanks I try to solve it ASAP!!!

**Comment by unaizorrilla** [comment]
Hi @wormst 

Checkout the code and perform some minor changes, I use dotmemory and I think is ok!, can you check 3.0.2 version of the UI and close this if issue is resolved?

**Comment by wormst** [comment]
You've probably meant version 3.0.**3**, but I can't see it available. Could you verify that?
Thanks in advance.

**Comment by unaizorrilla** [comment]
On NuGet right now 3.0.3 version

**Comment by wormst** [comment]
It seems that the issue still appears. You can try adding more liveness to configuration (~10) so the result will be better visible. 
Could you try running the project under Visual Studio and watch the Process Memory in Diagnostics Tools if it grows in time?

**Comment by unaizorrilla** [comment]
I use dotmemory and for me all is ok, I collect different snapshots and the memory consumption is ok in my side, I try to add more liveness and share with you my collection screenshots

**Comment by unaizorrilla** [comment]
Hi @wormst 

I do a new review in the hosted service and change the http client creation. Probably the better option is to use IHttpClientFactory ( I do it on new project, AspNetCore.HealthChecks ) but I don't spend a lot of time improving this project when the new version is already done.

I also check in dotmemory and the project is between  5 MB and 7 MB .NET Memory for a long time, the unmanaged memory is also stable between different executions.


Build is in process the new UI version is 3.0.4

**Comment by unaizorrilla** [comment]
Merged #99

**Comment by szogun1987** [comment]
I have created another PR https://github.com/Xabaril/BeatPulse/pull/101 it should fix memory leaks

**Comment by szogun1987** [comment]
@wormst @unaizorrilla  this issue probably can be closed.
